"""empty message

Revision ID: 20e161bf78a2
Revises: cbebf55cf916
Create Date: 2021-11-04 21:38:53.737362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e161bf78a2'
down_revision = 'cbebf55cf916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('newitem', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UpDATE todos SET newitem = 'nothing' WHERE newitem IS NULL")
    op.alter_column('todos', 'newitem', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'newitem')
    # ### end Alembic commands ###
