"""empty message

Revision ID: ea2f64026702
Revises: 037f1525d2b3
Create Date: 2021-11-08 22:19:27.351553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2f64026702'
down_revision = '037f1525d2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolist', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todolist SET completed = False WHERE completed IS NULL')
    op.alter_column('todolist', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolist', 'completed')
    # ### end Alembic commands ###
